services:
  dev:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
      args:
        VARIANT: ${ALMALINUX_VARIANT}
        DOTNET_VERSION: ${DOTNET_VERSION}
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    user: ${USER_UID}:${USER_GID}
    ports:
      - ${SSH_PORT}:22
    volumes:
      - projects:/home/${USER_NAME}/projects
      - ${HOME}/.ssh:/home/${USER_NAME}/.ssh:ro
      - /etc/ssh/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
    restart: unless-stopped

volumes:
  projects: